(in-package :orra.tests)

(defvar *tests* nil)

(defmacro deftest (name () &body body)
  `(progn
     (defun ,name ()
       ,@body)
     (pushnew ',name *tests*)
     ',name))

(defun is (condition &optional (message "Assertion failed."))
  (unless condition
    (error "~A" message)))

(defun collect-text-cells (cell)
  (let (texts)
    (labels ((visit (node)
               (when (typep node 'text-cell)
                 (push (orra::cell-text node) texts))
               (dolist (child (children-of node))
                 (visit child))))
      (visit cell))
    (nreverse texts)))

(defun find-text-cell-for-model (cell model-id)
  (labels ((visit (node)
             (or (when (and (typep node 'text-cell)
                            (cell-model node)
                            (string= (object-id (cell-model node))
                                     model-id)
                            (not (eq (orra::cell-role node) :heading)))
                   node)
                 (dolist (child (children-of node) nil)
                   (let ((found (visit child)))
                     (when found
                       (return found)))))))
    (visit cell)))

(defun find-first-node-of-type (root type)
  (labels ((visit (node)
             (or (when (typep node type)
                   node)
                 (dolist (child (typecase node
                                  (workspace (children-of node))
                                  (orra::composite-node (children-of node))
                                  (t nil))
                          nil)
                   (let ((found (visit child)))
                     (when found
                       (return found)))))))
    (visit root)))

(deftest text-buffer-editing ()
  (let ((buffer (make-text-buffer :content "abc" :cursor 1)))
    (insert-buffer-text buffer "Z")
    (is (string= "aZbc" (text-buffer-content buffer))
        "Insert should splice text at cursor.")
    (move-buffer-cursor-left buffer)
    (delete-buffer-forward buffer)
    (is (string= "abc" (text-buffer-content buffer))
        "Delete forward should remove the character at cursor.")
    (move-buffer-cursor-right buffer)
    (delete-buffer-backward buffer)
    (is (string= "ac" (text-buffer-content buffer))
        "Delete backward should remove the preceding character.")
    (is (= 1 (text-buffer-cursor buffer))
        "Cursor should stay within bounds.")))

(deftest text-buffer-multiline-navigation-and-history ()
  (let ((buffer (make-text-buffer
                 :content (format nil "alpha~%beta~%gamma")
                 :cursor 8)))
    (multiple-value-bind (line column)
        (buffer-cursor-line-column buffer)
      (is (= 1 line)
          "Cursor should report the expected line.")
      (is (= 2 column)
          "Cursor should report the expected column."))
    (move-buffer-cursor-home buffer)
    (is (= 6 (text-buffer-cursor buffer))
        "Home should move to the start of the current line.")
    (move-buffer-cursor-end buffer)
    (is (= 10 (text-buffer-cursor buffer))
        "End should move to the end of the current line.")
    (move-buffer-cursor-down buffer)
    (multiple-value-bind (line column)
        (buffer-cursor-line-column buffer)
      (is (= 2 line)
          "Down should move to the next line.")
      (is (= 4 column)
          "Down should preserve the current column when possible."))
    (move-buffer-cursor-up buffer)
    (multiple-value-bind (line column)
        (buffer-cursor-line-column buffer)
      (is (= 1 line)
          "Up should move back to the previous line.")
      (is (= 4 column)
          "Up should preserve the current column when possible."))
    (insert-buffer-text buffer "!")
    (is (string= (format nil "alpha~%beta!~%gamma")
                 (text-buffer-content buffer))
        "Insert should update multiline buffers.")
    (undo-buffer-edit buffer)
    (is (string= (format nil "alpha~%beta~%gamma")
                 (text-buffer-content buffer))
        "Undo should restore the previous snapshot.")
    (redo-buffer-edit buffer)
    (is (string= (format nil "alpha~%beta!~%gamma")
                 (text-buffer-content buffer))
        "Redo should reapply the undone snapshot.")))

(deftest printable-key-text-from-sym ()
  (is (string= "a" (orra::printable-key-text-from-sym 97 nil nil))
      "Lowercase letters should round-trip.")
  (is (string= "A" (orra::printable-key-text-from-sym 97 t nil))
      "Shift should uppercase letters.")
  (is (string= "A" (orra::printable-key-text-from-sym 97 nil t))
      "Caps lock should uppercase letters.")
  (is (string= "!" (orra::printable-key-text-from-sym 49 t nil))
      "Shifted digits should map to punctuation.")
  (is (string= "/" (orra::printable-key-text-from-sym 47 nil nil))
      "Printable punctuation should round-trip."))

(deftest common-lisp-source-parse-info ()
  (let ((info (parse-common-lisp-source
               (format nil "(list :hello :orra)~%(+ 20 22)"))))
    (is (null (getf info :error))
        "Valid Common Lisp source should parse without an error.")
    (is (= 2 (length (getf info :forms)))
        "Expected two top-level forms in the parse result.")))

(deftest common-lisp-source-parse-error-info ()
  (let ((info (parse-common-lisp-source "(list :hello :orra")))
    (is (getf info :error)
        "Malformed Common Lisp source should report a parse error.")
    (is (integerp (or (getf info :offset) 0))
        "Parse errors should report an offset when available.")))

(deftest property-inheritance ()
  (let* ((registry (make-object-registry))
         (prototype (make-paragraph :text "proto" :registry registry))
         (child (make-paragraph :text "child" :registry registry)))
    (setf (object-prototype child) prototype)
    (set-object-property prototype :font :serif)
    (is (eql :serif (object-property child :font))
        "Prototype property lookup failed.")))

(deftest notebook-to-cell-tree ()
  (let* ((registry (make-object-registry))
         (workspace (make-workspace :registry registry))
         (notebook (make-notebook :title "N" :registry registry))
         (section (make-section :title "S" :registry registry))
         (paragraph (make-paragraph :text "hello" :registry registry))
         (tree nil))
    (append-child workspace notebook)
    (append-child notebook section)
    (append-child section paragraph)
    (setf tree (build-workspace-cell-tree workspace registry))
    (is (= 2 (length (children-of tree)))
        "Workspace view should render header and notebook.")
    (is (typep (second (children-of tree)) 'container-cell)
        "Notebook cell should be a container.")))

(deftest application-shell-includes-inspector ()
  (let ((application (make-application :backend (make-null-backend))))
    (render-application application)
    (is (= 3 (length (children-of (application-root-cell application))))
        "Application shell should render workspace, inspector, and status.")
    (let ((texts (collect-text-cells (application-root-cell application))))
      (is (find "Inspector" texts :test #'string=)
          "Inspector header should be present.")
      (is (find (format nil "focused: ~A"
                        (format nil "~A ~A"
                                (object-kind (focused-model application))
                                (object-id (focused-model application))))
                texts
                :test #'string=)
          "Inspector should describe the focused model."))))

(deftest code-block-structure-preview-renders ()
  (let ((application (make-application :backend (make-null-backend))))
    (render-application application)
    (let ((texts (collect-text-cells (application-root-cell application))))
      (is (find "Parse OK  |  1 top-level form" texts :test #'string=)
          "Code blocks should render a parse status line.")
      (is (find "Selected form 1/1  |  list (3 items)" texts :test #'string=)
          "Code blocks should render the current selected top-level form.")
      (is (find "Structure" texts :test #'string=)
          "Code blocks with structure enabled should render a structure heading.")
      (is (find "> form 1: list (3 items)" texts :test #'string=)
          "Code blocks should render a structural summary for parsed forms."))))

(deftest inspector-describes-code-block-parse-state ()
  (let ((application (make-application :backend (make-null-backend))))
    (render-application application)
    (setf (orra::application-focused-model-id application)
          (object-id
           (find-first-node-of-type
            (application-workspace application)
            'code-block)))
    (render-application application)
    (let ((texts (collect-text-cells (application-root-cell application))))
      (is (find "parse: Parse OK  |  1 top-level form" texts :test #'string=)
          "Inspector should describe code-block parse status.")
      (is (find "structure: visible" texts :test #'string=)
          "Inspector should report whether structure preview is visible."))))

(deftest focus-navigation ()
  (let ((application (make-application :backend (make-null-backend))))
    (render-application application)
    (is (typep (focused-model application) 'paragraph)
        "Initial focus should prefer the first editable model.")
    (let ((first-focus (object-id (focused-model application))))
      (focus-next-model application)
      (is (not (string= first-focus
                        (object-id (focused-model application))))
          "Focus should advance to a different object.")
      (focus-previous-model application)
      (is (string= first-focus
                   (object-id (focused-model application)))
          "Focus should move back to the original object."))))

(deftest click-focused-editable-model-starts-editing ()
  (let ((application (make-application :backend (make-null-backend))))
    (render-application application)
    (let* ((focused (focused-model application))
           (cell (find-text-cell-for-model (application-root-cell application)
                                           (object-id focused)))
           (bounds (cell-bounds cell)))
      (orra::focus-model-at-pixel application
                                  (orra::bounds-x bounds)
                                  (orra::bounds-y bounds)))
    (is (editing-active-p application)
        "Clicking the already-focused paragraph should begin editing.")))

(deftest multiline-paragraph-renders-with-multiple-rows ()
  (let ((application (make-application :backend (make-null-backend))))
    (setf (paragraph-text (focused-model application))
          (format nil "alpha~%beta"))
    (render-application application)
    (let* ((cell (find-text-cell-for-model (application-root-cell application)
                                           (object-id (focused-model application))))
           (bounds (cell-bounds cell)))
      (is (= 2 (orra::bounds-height bounds))
          "Multiline paragraph cells should reserve one row per line."))))

(deftest clicking-focused-multiline-cell-places-cursor ()
  (let ((application (make-application :backend (make-null-backend))))
    (setf (paragraph-text (focused-model application))
          (format nil "alpha~%beta"))
    (render-application application)
    (let* ((cell (find-text-cell-for-model (application-root-cell application)
                                           (object-id (focused-model application))))
           (bounds (cell-bounds cell)))
      (orra::focus-model-at-pixel application
                                  (+ (orra::bounds-x bounds) 2)
                                  (+ (orra::bounds-y bounds) 1))
      (is (editing-active-p application)
          "Clicking focused multiline text should begin editing.")
      (is (= 7 (text-buffer-cursor
                (orra::application-active-text-buffer application)))
          "Cursor placement should respect the clicked line and column."))))

(deftest long-line-editing-keeps-cursor-visible ()
  (let ((application (make-application :backend (make-null-backend)))
        (content (with-output-to-string (stream)
                   (loop for index from 0 below 80
                         do (format stream "~2,'0D" index)))))
    (setf (paragraph-text (focused-model application)) content)
    (begin-editing-focused-model application)
    (render-application application)
    (let ((*application* application))
      (let* ((cell (find-text-cell-for-model (application-root-cell application)
                                             (object-id (focused-model application))))
             (visible-line (first (orra::visible-lines-for-cell cell))))
        (is (search "|" visible-line)
            "The active cursor should stay visible even when the line is wider than the cell.")))))

(deftest edit-history-persists-across-editing-sessions ()
  (let* ((application (make-application :backend (make-null-backend)))
         (original (paragraph-text (focused-model application))))
    (begin-editing-focused-model application)
    (insert-into-active-buffer application " More")
    (stop-editing application)
    (begin-editing-focused-model application)
    (undo-active-buffer-edit application)
    (is (string= original (paragraph-text (focused-model application)))
        "Undo history should survive leaving and re-entering the same editable model.")
    (redo-active-buffer-edit application)
    (is (string= (concatenate 'string original " More")
                 (paragraph-text (focused-model application)))
        "Redo history should survive leaving and re-entering the same editable model.")))

(deftest toggle-code-structure-command ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (find-first-node-of-type
                 (application-workspace application)
                 'code-block)))
    (render-application application)
    (is (code-block-structure-visible-p block)
        "Scratch code blocks should start with structure preview enabled.")
    (invoke-command application 'toggle-code-structure (object-id block))
    (is (not (code-block-structure-visible-p block))
        "Toggle command should hide the structural preview.")
    (is (not (find "Structure"
                   (collect-text-cells (application-root-cell application))
                   :test #'string=))
        "Hidden structural previews should disappear from the rendered cell tree.")
    (invoke-command application 'toggle-code-structure (object-id block))
    (is (code-block-structure-visible-p block)
        "Toggle command should restore the structural preview.")))

(deftest code-form-selection-navigation ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application
                                'append-code-block
                                (format nil "(list :alpha)~%(+ 20 22)"))))
    (render-application application)
    (is (= 0 (code-block-selected-form-index block))
        "Multi-form code blocks should default to the first top-level form.")
    (invoke-command application 'select-next-code-form (object-id block))
    (is (= 1 (code-block-selected-form-index block))
        "Next-form navigation should advance the structural selection.")
    (invoke-command application 'select-next-code-form (object-id block))
    (is (= 1 (code-block-selected-form-index block))
        "Next-form navigation should clamp at the last top-level form.")
    (invoke-command application 'select-previous-code-form (object-id block))
    (is (= 0 (code-block-selected-form-index block))
        "Previous-form navigation should move back to the earlier form.")
    (invoke-command application 'select-previous-code-form (object-id block))
    (is (= 0 (code-block-selected-form-index block))
        "Previous-form navigation should clamp at the first top-level form.")))

(deftest code-form-selection-renders-and-reaches-inspector ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application
                                'append-code-block
                                (format nil "(list :alpha)~%(+ 20 22)"))))
    (set-object-property block :show-structure t)
    (invoke-command application 'select-next-code-form (object-id block))
    (setf (orra::application-focused-model-id application)
          (object-id block))
    (render-application application)
    (let ((texts (collect-text-cells (application-root-cell application))))
      (is (find "Selected form 2/2  |  list (3 items)" texts :test #'string=)
          "Code blocks should render the current top-level structural selection.")
      (is (find "> form 2: list (3 items)" texts :test #'string=)
          "The structure preview should visibly mark the selected top-level form.")
      (is (find "selection: Selected form 2/2  |  list (3 items)"
                texts
                :test #'string=)
          "The inspector should describe the selected top-level form.")
      (is (find "selected-form-index: 1" texts :test #'string=)
          "The inspector should show the selected form index."))))

(deftest nested-code-form-selection-navigation ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application
                                'append-code-block
                                "(list (+ 1 2) (* 3 4))")))
    (is (equal '(0) (code-block-selected-form-path block))
        "Code blocks should default to selecting the first top-level form path.")
    (invoke-command application 'select-child-code-form (object-id block))
    (is (equal '(0 0) (code-block-selected-form-path block))
        "Descending should select the first child of the current form.")
    (invoke-command application 'select-next-code-form (object-id block))
    (is (equal '(0 1) (code-block-selected-form-path block))
        "Sibling navigation should operate at the current selection depth.")
    (invoke-command application 'select-child-code-form (object-id block))
    (is (equal '(0 1 0) (code-block-selected-form-path block))
        "Nested descent should continue selecting the first child.")
    (invoke-command application 'select-parent-code-form (object-id block))
    (is (equal '(0 1) (code-block-selected-form-path block))
        "Ascending should return to the parent selection.")
    (is (string= "Selected path 1.2  |  list (3 items)"
                 (code-block-selection-status-line block))
        "Nested selections should report their structural path.")))

(deftest nested-code-form-selection-renders-and-reaches-inspector ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application
                                'append-code-block
                                "(list (+ 1 2) (* 3 4))")))
    (set-object-property block :show-structure t)
    (invoke-command application 'select-child-code-form (object-id block))
    (invoke-command application 'select-next-code-form (object-id block))
    (setf (orra::application-focused-model-id application)
          (object-id block))
    (render-application application)
    (let ((texts (collect-text-cells (application-root-cell application))))
      (is (find "Selected path 1.2  |  list (3 items)" texts :test #'string=)
          "Nested selections should render their structural path.")
      (is (find-if (lambda (text)
                     (search "> [1]: list (3 items)" text))
                   texts)
          "The structure preview should visibly mark the selected nested form.")
      (is (find "selection: Selected path 1.2  |  list (3 items)"
                texts
                :test #'string=)
          "The inspector should describe the selected nested form.")
      (is (find "selected-form-path: (0 1)" texts :test #'string=)
          "The inspector should show the selected structural path."))))

(deftest code-block-editing-starts-at-selected-structural-form ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application
                                'append-code-block
                                "(list (+ 1 2) (* 3 4))")))
    (invoke-command application 'select-child-code-form (object-id block))
    (invoke-command application 'select-next-code-form (object-id block))
    (setf (orra::application-focused-model-id application)
          (object-id block))
    (begin-editing-focused-model application)
    (is (editing-active-p application)
        "Focused code blocks should enter text edit mode.")
    (is (= 6 (text-buffer-cursor
              (orra::application-active-text-buffer application)))
        "Code-block text editing should start at the selected structural form.")
    (stop-editing application)))

(deftest code-block-edit-cursor-updates-structural-selection ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application
                                'append-code-block
                                "(list (+ 1 2) (* 3 4))")))
    (invoke-command application 'select-child-code-form (object-id block))
    (invoke-command application 'select-next-code-form (object-id block))
    (setf (orra::application-focused-model-id application)
          (object-id block))
    (begin-editing-focused-model application)
    (move-active-buffer-cursor-right application)
    (is (equal '(0 1 0) (code-block-selected-form-path block))
        "Moving inside the selected subform should tighten selection to the deepest enclosing child.")
    (move-active-buffer-cursor-right application)
    (move-active-buffer-cursor-right application)
    (is (equal '(0 1 1) (code-block-selected-form-path block))
        "Moving onto another nested atom should retarget the structural selection.")
    (stop-editing application)))

(deftest code-form-selection-navigation-stays-live-while-editing ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application
                                'append-code-block
                                "(list (+ 1 2) (* 3 4))")))
    (setf (orra::application-focused-model-id application)
          (object-id block))
    (begin-editing-focused-model application)
    (invoke-command application 'select-child-code-form (object-id block))
    (invoke-command application 'select-next-code-form (object-id block))
    (is (editing-active-p application)
        "Structural selection commands should keep code-block edit mode active.")
    (is (equal '(0 1) (code-block-selected-form-path block))
        "Selection commands should still update the structural path while editing.")
    (is (= 6
           (text-buffer-cursor
            (orra::application-active-text-buffer application)))
        "Selection commands should move the live cursor to the selected form.")
    (invoke-command application 'select-parent-code-form (object-id block))
    (is (= 0
           (text-buffer-cursor
            (orra::application-active-text-buffer application)))
        "Ascending the structural selection should retarget the live cursor.")
    (stop-editing application)))

(deftest structural-code-edit-keeps-active-buffer-in-sync ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application
                                'append-code-block
                                "(list (+ 1 2) (* 3 4))")))
    (invoke-command application 'select-child-code-form (object-id block))
    (invoke-command application 'select-next-code-form (object-id block))
    (setf (orra::application-focused-model-id application)
          (object-id block))
    (begin-editing-focused-model application)
    (invoke-command application 'wrap-code-form (object-id block))
    (is (editing-active-p application)
        "Structural rewrites should keep code-block edit mode active.")
    (is (string= "(LIST (PROGN (+ 1 2)) (* 3 4))"
                 (code-block-source block))
        "Wrapping while editing should still rewrite the selected form.")
    (is (string= (code-block-source block)
                 (text-buffer-content
                  (orra::application-active-text-buffer application)))
        "The active text buffer should stay synchronized with structural rewrites.")
    (is (= 6
           (text-buffer-cursor
            (orra::application-active-text-buffer application)))
        "The live cursor should remain anchored to the rewritten selected form.")
    (undo-active-buffer-edit application)
    (is (string= "(list (+ 1 2) (* 3 4))"
                 (code-block-source block))
        "Undo in the active edit session should reverse the structural rewrite.")
    (stop-editing application)))

(deftest deleting-selected-code-form-rewrites-source ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application
                                'append-code-block
                                (format nil "(list :alpha)~%(+ 20 22)"))))
    (invoke-command application 'select-next-code-form (object-id block))
    (invoke-command application 'delete-code-form (object-id block))
    (is (string= "(LIST :ALPHA)" (code-block-source block))
        "Deleting the selected top-level form should rewrite the block source.")
    (is (= 0 (code-block-selected-form-index block))
        "Deleting the last top-level form should clamp selection to the remaining form.")
    (is (string= "Selected form 1/1  |  list (2 items)"
                 (code-block-selection-status-line block))
        "Selection status should update after structural deletion.")))

(deftest deleting-nested-code-form-rewrites-source ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application
                                'append-code-block
                                "(list :alpha :beta :gamma)")))
    (invoke-command application 'select-child-code-form (object-id block))
    (invoke-command application 'select-next-code-form (object-id block))
    (invoke-command application 'select-next-code-form (object-id block))
    (invoke-command application 'delete-code-form (object-id block))
    (is (string= "(LIST :ALPHA :GAMMA)" (code-block-source block))
        "Deleting a nested selected form should rewrite the block source.")
    (is (equal '(0 2) (code-block-selected-form-path block))
        "Nested deletion should keep selection on the surviving sibling at the same depth.")))

(deftest wrap-and-splice-code-form-rewrite-source ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application 'append-code-block "(+ 20 22)")))
    (invoke-command application 'wrap-code-form (object-id block))
    (is (string= "(PROGN (+ 20 22))" (code-block-source block))
        "Wrapping should rewrite the selected form as a PROGN wrapper.")
    (invoke-command application 'splice-code-form (object-id block))
    (is (string= "(+ 20 22)" (code-block-source block))
        "Splicing should remove the PROGN wrapper and restore the body form.")
    (is (= 0 (code-block-selected-form-index block))
        "Selection should stay on the first form after wrap/splice.")))

(deftest wrap-and-splice-nested-code-form-rewrite-source ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application
                                'append-code-block
                                "(list (+ 20 22) :done)")))
    (invoke-command application 'select-child-code-form (object-id block))
    (invoke-command application 'select-next-code-form (object-id block))
    (invoke-command application 'wrap-code-form (object-id block))
    (is (string= "(LIST (PROGN (+ 20 22)) :DONE)" (code-block-source block))
        "Wrapping a nested selection should rewrite only the selected nested form.")
    (invoke-command application 'splice-code-form (object-id block))
    (is (string= "(LIST (+ 20 22) :DONE)" (code-block-source block))
        "Splicing a nested selection should remove only the selected nested wrapper.")
    (is (equal '(0 1) (code-block-selected-form-path block))
        "Selection should stay on the nested form after wrap/splice.")))

(deftest structural-code-edit-invalidates-existing-result ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application 'append-code-block "(+ 20 22)"))
         (result (invoke-command application 'evaluate-code-block
                                 (object-id block))))
    (is (eq :ok (result-block-status result))
        "Expected a successful result before structural edits.")
    (invoke-command application 'wrap-code-form (object-id block))
    (is (eq :stale (result-block-status result))
        "Structural source edits should invalidate previous evaluation results.")
    (is (string= "Result invalidated by source changes."
                 (result-block-presentation result))
        "Stale results should explain why they are no longer current.")
    (render-application application)
    (is (find ".. Result invalidated by source changes."
              (collect-text-cells (application-root-cell application))
              :test #'string=)
        "Invalidated results should render explicitly in the workspace.")))

(deftest structural-code-edits-enter-text-edit-history ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application 'append-code-block "(+ 20 22)")))
    (invoke-command application 'wrap-code-form (object-id block))
    (setf (orra::application-focused-model-id application)
          (object-id block))
    (begin-editing-focused-model application)
    (undo-active-buffer-edit application)
    (is (string= "(+ 20 22)" (code-block-source block))
        "Undo should treat a structural rewrite as part of the editable code history.")
    (redo-active-buffer-edit application)
    (is (string= "(PROGN (+ 20 22))" (code-block-source block))
        "Redo should reapply the structural rewrite from code-block edit history.")
    (stop-editing application)))

(deftest structural-code-edits-preserve-prior-text-history ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application 'append-code-block "(+ 20 22)")))
    (setf (orra::application-focused-model-id application)
          (object-id block))
    (begin-editing-focused-model application)
    (move-active-buffer-cursor-end application)
    (move-active-buffer-cursor-left application)
    (insert-into-active-buffer application "0")
    (stop-editing application)
    (invoke-command application 'wrap-code-form (object-id block))
    (begin-editing-focused-model application)
    (undo-active-buffer-edit application)
    (is (string= "(+ 20 220)" (code-block-source block))
        "Undo after a structural rewrite should restore the prior text-edited source first.")
    (undo-active-buffer-edit application)
    (is (string= "(+ 20 22)" (code-block-source block))
        "Earlier text edits should remain reachable beneath structural history entries.")
    (redo-active-buffer-edit application)
    (is (string= "(+ 20 220)" (code-block-source block))
        "Redo should restore the earlier text edit before reapplying later structural edits.")
    (redo-active-buffer-edit application)
    (is (string= "(+ 20 (PROGN 220))" (code-block-source block))
        "Redo should reapply the structural rewrite after the prior text edit.")
    (stop-editing application)))

(deftest invalid-code-evaluation-produces-error-result ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application 'append-code-block "de"))
         (result (invoke-command application 'evaluate-code-block
                                 (object-id block))))
    (is (typep result 'result-block)
        "Evaluating invalid code should still produce a result block.")
    (is (eq :error (result-block-status result))
        "Invalid code should mark the result block as an error.")
    (is (search "Evaluation error:" (result-block-presentation result))
        "Runtime failures should be rendered as evaluation errors.")
    (render-application application)
    (is (find-if (lambda (text)
                   (search "!! Evaluation error:" text))
                 (collect-text-cells (application-root-cell application)))
        "Error results should render in the workspace instead of entering the debugger.")))

(deftest malformed-code-evaluation-produces-error-result ()
  (let* ((application (make-application :backend (make-null-backend)))
         (block (invoke-command application 'append-code-block "(list :hello"))
         (result (invoke-command application 'evaluate-code-block
                                 (object-id block))))
    (is (eq :error (result-block-status result))
        "Reader failures should mark the result block as an error.")
    (is (search "Parse error@" (result-block-presentation result))
        "Malformed source should reuse the parse error message as the result.")))

(deftest editing-focused-model ()
  (let ((application (make-application :backend (make-null-backend))))
    (render-application application)
    (is (typep (focused-model application) 'paragraph)
        "Expected to focus the initial paragraph.")
    (begin-editing-focused-model application)
    (insert-into-active-buffer application " More")
    (is (string= "This image is live. Commands and objects are data. More"
                 (paragraph-text (focused-model application)))
        "Paragraph text should update during editing.")
    (stop-editing application)
    (is (not (editing-active-p application))
        "Editing state should clear when stopped.")))

(deftest persistence-round-trip ()
  (let* ((application (make-application))
         (block nil))
    (setf block (invoke-command application 'append-code-block "(+ 20 22)"))
    (render-application application)
    (loop repeat 8
          until (string= (object-id (focused-model application))
                         (object-id block))
          do (focus-next-model application))
    (begin-editing-focused-model application)
    (move-active-buffer-cursor-end application)
    (move-active-buffer-cursor-left application)
    (insert-into-active-buffer application "0")
    (stop-editing application)
    (invoke-command application 'evaluate-code-block (object-id block))
    (uiop:with-temporary-file (:pathname path :keep t)
      (unwind-protect
           (progn
             (save-workspace-to-file (application-workspace application)
                                     path
                                     :registry (application-registry application))
             (let* ((registry (make-object-registry))
                    (workspace (load-workspace-from-file path :registry registry))
                    (loaded-notebook (root-notebook workspace))
                    (loaded-section (first (children-of loaded-notebook)))
                    (loaded-block (find-if (lambda (object)
                                             (and (typep object 'code-block)
                                                  (string= "(+ 20 220)"
                                                           (code-block-source
                                                            object))))
                                           (children-of loaded-section))))
               (is (typep loaded-block 'code-block)
                   "Expected to load a code block.")
               (is (string= "240"
                            (result-block-presentation
                             (code-block-result loaded-block)))
                   "Expected persisted evaluation result.")
               (is (eq :ok
                       (result-block-status
                        (code-block-result loaded-block)))
                   "Expected persisted evaluation status.")))
        (when (probe-file path)
          (delete-file path))))))

(defun run-all-tests ()
  (let ((passed 0)
        (failed 0))
    (dolist (test (reverse *tests*))
      (handler-case
          (progn
            (funcall test)
            (incf passed)
            (format t "~&PASS ~A~%" test))
        (error (condition)
          (incf failed)
          (format t "~&FAIL ~A~%  ~A~%" test condition))))
    (format t "~&~D passed, ~D failed.~%" passed failed)
    (when (plusp failed)
      (error "Test failures encountered."))
    t))
